/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // main: [{ type: "autogenerated", dirName: "." }],

  // But you can create a sidebar manually
  main: [
    "intro",
    {
      type: 'category',
      label: '基础语法',
      
      items: [
        'syntax/basics',
        'syntax/function',
        'syntax/class',
        'syntax/interface',
        'syntax/generic-type-and-function',
        'syntax/null-safety',
        'syntax/module',
        'syntax/keyword',
        'syntax/annotation',
      ],
    },
    {
      type: 'category',
      label: '基础类库',
      collapsed: true,
      items: [
        'library/xml',
        'library/json',
        'library/linear-container',
        'library/nonlinear-container',
      ],
    },
    {
      type: 'category',
      label: '模块化',
      collapsed: true,
      items: [
        'module/types',
        'module/dynamic-import',
        'module/lazy-import',
      ],
    },
    {
      type: 'category',
      label: '并发',
      collapsed: true,
      items: [
        'concurrency/asynchronous-concurrency',
        'concurrency/multi-thread-concurrency',
        'concurrency/inter-thread-communication',
        'concurrency/cases',
      ],
    },
    {
      type: 'category',
      label: '工具链',
      collapsed: true,
      items: [
        'toolchain/ark-bytecode',
        'toolchain/disassembly-tool',
        'toolchain/obfuscation',
        'toolchain/compile-configuration',
      ],
    },
    "gc",
    "cross-language",
    {
      type: 'category',
      label: '编程规范及实践',
      collapsed: true,
      items: [
        'specification/code-style',
        'specification/programming-practice',
        'specification/high-performance-programming-practice',
      ],
    },
    {
      type: 'category',
      label: '从其他语言迁移',
      collapsed: true,
      items: [
        'migration/typescript',
        'migration/java',
        'migration/swift',
      ],
    },
    "api",
  ],
};

module.exports = sidebars;
